import type { Metadata } from "next";
import {
    EB_Garamond,
    Homemade_Apple,
    Gloock,
    Libre_Baskerville,
} from "next/font/google";
import "./globals.css";

const libreBaskerville = Libre_Baskerville({
    // weight: ["400", "700"],
    variable: "--font-libre-baskerville",
    subsets: ["latin"],
});

const homemadeApple = Homemade_Apple({
    weight: ["400"],
    variable: "--font-homemade-apple",
    subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
    variable: "--font-eb-garamond",
    subsets: ["latin"],
});

const gloock = Gloock({
    weight: ["400"],
    variable: "--font-gloock",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${homemadeApple.variable} ${ebGaramond.variable} ${gloock.variable} ${libreBaskerville.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col overflow-x-hidden">
                {children}
            </body>
        </html>
    );
}
